"""Flat financial-math API."""

from .annuities import (
    nper_anualidad_vf,
    nper_anualidad_vp,
    nper_gradiente_arit_vf,
    nper_gradiente_arit_vp,
    nper_gradiente_geo_vf,
    nper_gradiente_geo_vp,
    vf_anualidad_continua,
    vf_anualidad_efectiva,
    vf_anualidad_nominal,
    vf_gradiente_aritmetico,
    vf_gradiente_geo,
    vp_anualidad_continua,
    vp_anualidad_efectiva,
    vp_anualidad_nominal,
    vp_gradiente_aritmetico,
    vp_gradiente_geo,
    vp_perpetuidad,
)
from .bonds import precio_bono, riesgo_bono, tasa_rendimiento_bono
from .cashflows import calcular_vp_dividendos, calcular_vp_flujos_irregulares
from .corporate import (
    beta_alpha_from_returns,
    capm_cost_of_equity,
    dcf_sensitivity_matrix,
    dcf_valuation,
    weighted_average_cost_of_capital,
)
from .equity import rendimiento_requerido_accion, valuacion_gordon_shapiro, valuacion_multiplos
from .loans import tabla_amortizacion
from .portfolio import (
    equal_weight_portfolio,
    evaluate_custom_portfolio,
    monte_carlo_portfolio_cloud,
    mvsk_neg_utility,
    mvsk_portfolio,
    portfolio_return,
    portfolio_sharpe,
    portfolio_volatility,
    risk_parity_objective,
    risk_parity_portfolio,
)
from .rates import (
    generar_tabla_reinversion,
    tasa_efectiva_a_nominal,
    tasa_instantanea_a_efectiva,
    tasa_instantanea_a_nominal,
    tasa_nominal_a_efectiva,
    tasa_nominal_a_instantanea,
    tasa_nominal_m_a_nominal_p,
)
from .risk import calcular_var_cvar_montecarlo, calcular_var_parametrico
from .tvm import (
    desglosar_periodos,
    numero_periodos,
    tasa_rendimiento,
    valor_futuro,
    valor_futuro_continuo,
    valor_presente,
    valor_presente_continuo,
)

__all__ = [
    "tasa_nominal_a_efectiva",
    "tasa_efectiva_a_nominal",
    "tasa_nominal_a_instantanea",
    "tasa_instantanea_a_efectiva",
    "tasa_instantanea_a_nominal",
    "tasa_nominal_m_a_nominal_p",
    "generar_tabla_reinversion",
    "valor_futuro",
    "valor_futuro_continuo",
    "valor_presente",
    "valor_presente_continuo",
    "numero_periodos",
    "tasa_rendimiento",
    "desglosar_periodos",
    "vf_anualidad_efectiva",
    "vf_anualidad_nominal",
    "vf_anualidad_continua",
    "vp_anualidad_efectiva",
    "vp_anualidad_nominal",
    "vp_anualidad_continua",
    "vp_perpetuidad",
    "vf_gradiente_geo",
    "vp_gradiente_geo",
    "vp_gradiente_aritmetico",
    "vf_gradiente_aritmetico",
    "nper_anualidad_vf",
    "nper_anualidad_vp",
    "nper_gradiente_geo_vf",
    "nper_gradiente_geo_vp",
    "nper_gradiente_arit_vf",
    "nper_gradiente_arit_vp",
    "tabla_amortizacion",
    "precio_bono",
    "tasa_rendimiento_bono",
    "riesgo_bono",
    "valuacion_gordon_shapiro",
    "rendimiento_requerido_accion",
    "valuacion_multiplos",
    "calcular_vp_dividendos",
    "calcular_vp_flujos_irregulares",
    "calcular_var_parametrico",
    "calcular_var_cvar_montecarlo",
    "capm_cost_of_equity",
    "weighted_average_cost_of_capital",
    "dcf_valuation",
    "dcf_sensitivity_matrix",
    "beta_alpha_from_returns",
    "portfolio_return",
    "portfolio_volatility",
    "portfolio_sharpe",
    "equal_weight_portfolio",
    "risk_parity_objective",
    "risk_parity_portfolio",
    "mvsk_neg_utility",
    "mvsk_portfolio",
    "monte_carlo_portfolio_cloud",
    "evaluate_custom_portfolio",
]
