"""Flat financial-math API."""

from .annuities import (
    arithmetic_gradient_future_value,
    arithmetic_gradient_present_value,
    continuous_annuity_future_value,
    continuous_annuity_present_value,
    effective_annuity_future_value,
    effective_annuity_present_value,
    geometric_gradient_future_value,
    geometric_gradient_present_value,
    nominal_annuity_future_value,
    nominal_annuity_present_value,
    periods_for_annuity_future_value,
    periods_for_annuity_present_value,
    periods_for_arithmetic_gradient_future_value,
    periods_for_arithmetic_gradient_present_value,
    periods_for_geometric_gradient_future_value,
    periods_for_geometric_gradient_present_value,
    perpetuity_present_value,
)
from .bonds import bond_price, bond_risk, bond_yield
from .cashflows import present_value_of_dividends, present_value_of_irregular_cashflows
from .corporate import (
    beta_alpha_from_returns,
    capm_cost_of_equity,
    dcf_sensitivity_matrix,
    dcf_valuation,
    weighted_average_cost_of_capital,
)
from .equity import gordon_shapiro_valuation, multiples_valuation, required_equity_return
from .loans import amortization_schedule
from .portfolio import (
    equal_weight_portfolio,
    evaluate_custom_portfolio,
    evaluate_custom_portfolio_from_prices,
    historical_mean_returns,
    log_return_volatility,
    max_sharpe_portfolio,
    min_variance_portfolio,
    monte_carlo_portfolio_cloud,
    mvsk_neg_utility,
    mvsk_portfolio,
    optimize_portfolio_strategies,
    portfolio_return,
    portfolio_sharpe,
    portfolio_volatility,
    risk_parity_objective,
    risk_parity_portfolio,
    sample_covariance,
)
from .rates import (
    continuous_to_effective_rate,
    continuous_to_nominal_rate,
    convert_nominal_frequency,
    effective_to_nominal_rate,
    nominal_to_continuous_rate,
    nominal_to_effective_rate,
    reinvestment_table,
)
from .risk import monte_carlo_var_cvar, parametric_var
from .tvm import (
    continuous_future_value,
    continuous_present_value,
    decompose_periods,
    future_value,
    number_of_periods,
    present_value,
    rate_of_return,
)

__all__ = [
    "nominal_to_effective_rate",
    "effective_to_nominal_rate",
    "nominal_to_continuous_rate",
    "continuous_to_effective_rate",
    "continuous_to_nominal_rate",
    "convert_nominal_frequency",
    "reinvestment_table",
    "future_value",
    "continuous_future_value",
    "present_value",
    "continuous_present_value",
    "number_of_periods",
    "rate_of_return",
    "decompose_periods",
    "effective_annuity_future_value",
    "nominal_annuity_future_value",
    "continuous_annuity_future_value",
    "effective_annuity_present_value",
    "nominal_annuity_present_value",
    "continuous_annuity_present_value",
    "perpetuity_present_value",
    "geometric_gradient_future_value",
    "geometric_gradient_present_value",
    "periods_for_annuity_future_value",
    "periods_for_annuity_present_value",
    "periods_for_geometric_gradient_future_value",
    "periods_for_geometric_gradient_present_value",
    "arithmetic_gradient_present_value",
    "arithmetic_gradient_future_value",
    "periods_for_arithmetic_gradient_future_value",
    "periods_for_arithmetic_gradient_present_value",
    "amortization_schedule",
    "bond_price",
    "bond_yield",
    "bond_risk",
    "gordon_shapiro_valuation",
    "required_equity_return",
    "multiples_valuation",
    "present_value_of_dividends",
    "present_value_of_irregular_cashflows",
    "parametric_var",
    "monte_carlo_var_cvar",
    "capm_cost_of_equity",
    "weighted_average_cost_of_capital",
    "dcf_valuation",
    "dcf_sensitivity_matrix",
    "beta_alpha_from_returns",
    "historical_mean_returns",
    "sample_covariance",
    "log_return_volatility",
    "portfolio_return",
    "portfolio_volatility",
    "portfolio_sharpe",
    "equal_weight_portfolio",
    "max_sharpe_portfolio",
    "min_variance_portfolio",
    "risk_parity_objective",
    "risk_parity_portfolio",
    "mvsk_neg_utility",
    "mvsk_portfolio",
    "monte_carlo_portfolio_cloud",
    "evaluate_custom_portfolio",
    "evaluate_custom_portfolio_from_prices",
    "optimize_portfolio_strategies",
]
