"""Flat derivatives-pricing API."""

from .exotics import (
    arithmetic_asian_options,
    asset_or_nothing_options,
    cash_or_nothing_options,
    compound_options,
    down_and_out_barrier_option,
    exchange_options,
    exotic_payoff_leg,
    floating_lookback_options,
    gap_options,
    geometric_asian_options,
    perpetual_option,
    simple_chooser_option,
)
from .forwards import (
    commodity_forward_price,
    forward_contract_value,
    forward_price,
    forward_price_with_continuous_dividend,
    forward_price_with_discrete_dividends,
    forward_price_with_yield,
    fra,
    fx_forward_price,
    live_forward_value,
    simple_forward_price,
)
from .strategies import option_payoff_leg, strategy_profile
from .trees import binomial_tree, crr_binomial_tree
from .vanilla import (
    black_76,
    black_scholes,
    bsm_d1_d2,
    bsm_greeks,
    bsm_option_prices,
    calculate_greeks,
    implied_volatility_bsm,
    second_order_greeks,
)

__all__ = [
    "forward_price",
    "forward_price_with_yield",
    "forward_contract_value",
    "simple_forward_price",
    "forward_price_with_continuous_dividend",
    "forward_price_with_discrete_dividends",
    "commodity_forward_price",
    "fx_forward_price",
    "live_forward_value",
    "fra",
    "bsm_option_prices",
    "bsm_greeks",
    "black_scholes",
    "black_76",
    "bsm_d1_d2",
    "calculate_greeks",
    "second_order_greeks",
    "implied_volatility_bsm",
    "binomial_tree",
    "crr_binomial_tree",
    "gap_options",
    "cash_or_nothing_options",
    "asset_or_nothing_options",
    "down_and_out_barrier_option",
    "arithmetic_asian_options",
    "geometric_asian_options",
    "floating_lookback_options",
    "compound_options",
    "exchange_options",
    "exotic_payoff_leg",
    "simple_chooser_option",
    "perpetual_option",
    "option_payoff_leg",
    "strategy_profile",
]
